*.sh.in: exit on the first error and refactoring

diff --git a/test/ihklib/blackbox/src/ihk_os_makedumpfile06.sh.in b/test/ihklib/blackbox/src/ihk_os_makedumpfile06.sh.in
--- a/test/ihklib/blackbox/src/ihk_os_makedumpfile06.sh.in
+++ b/test/ihklib/blackbox/src/ihk_os_makedumpfile06.sh.in
@@ -9,23 +9,13 @@ fi
 
 . @CMAKE_INSTALL_PREFIX@/bin/util.sh
 
-for i in {0..1}; do
-    sudo @CMAKE_INSTALL_PREFIX@/bin/ihk_os_makedumpfile06 -u $(id -u) -g $(id -g) -i $i -f ${WORKDIR}/dump
-    ret=$?
+sudo @CMAKE_INSTALL_PREFIX@/bin/ihk_os_makedumpfile06 -u $(id -u) -g $(id -g) -i $i -f ${WORKDIR}/dump || exit $?
 
-    if [ $ret -ne 0 ]; then
-	break;
-    fi
+check_dump ${WORKDIR}/dump $i || exit $?
 
-    check_dump ${WORKDIR}/dump $i
-    if [ $ret -ne 0 ]; then
-	break;
-    fi
+sudo rm -f ${WORKDIR}/dump
 
-    sudo rm -f ${WORKDIR}/dump
+# clean up
+sudo @CMAKE_INSTALL_PREFIX@/bin/ihk_os_makedumpfile06 -u $(id -u) -g $(id -g) -i $i -f ${WORKDIR}/dump -c || exit $?
 
-    # clean up
-    sudo @CMAKE_INSTALL_PREFIX@/bin/ihk_os_makedumpfile06 -u $(id -u) -g $(id -g) -i $i -f ${WORKDIR}/dump -c
-done
-
-exit $ret
+exit 0
